/** Visible wording of the work dashboard, in one place (DESIGN.md §0). */
export const WORK_TEXT = {
  day: 'Ma journée',
  dayEmpty: 'Rien de prévu pour aujourd’hui',
  dayEmptyHint: 'Ajoute des tâches depuis « À prendre » ou « En cours » : elles se rangent ici, dans l’ordre où tu veux les faire.',
  inProgress: 'En cours',
  inProgressEmpty: 'Aucune tâche en cours.',
  next: 'À prendre',
  nextHint: 'La prochaine tâche réalisable de chaque plan actif.',
  nextEmpty: 'Aucun plan actif n’a de tâche prête.',
  chains: 'Chaînes',
  chainsHint: 'Les plans actifs et leur exécution.',
  chainsEmpty: 'Aucun plan en cours.',
  blocked: 'Bloqué',
  addToDay: 'Ajouter à ma journée',
  removeFromDay: 'Retirer de ma journée',
  moveUp: 'Monter',
  moveDown: 'Descendre',
  start: 'Démarrer',
  complete: 'Terminer',
  completeAria: (t: string) => `Marquer « ${t} » comme terminée`,
  launch: 'Lancer la chaîne',
  relaunch: 'Relancer la chaîne',
  launching: 'Lancement…',
  launched: 'Chaîne lancée',
  started: 'Tâche démarrée',
  completed: 'Tâche terminée',
  actionFailed: 'L’action n’a pas abouti.',
  neverRun: 'Jamais lancée',
  untitled: 'Tâche sans titre',
  loadError: 'Le tableau de bord n’a pas pu être chargé.',
  retry: 'Réessayer',
  stale: 'Actualisation impossible : les données affichées peuvent être périmées.',
  summary: {
    planned: (n: number) => `${n} prévue${n > 1 ? 's' : ''}`,
    done: (n: number) => `${n} faite${n > 1 ? 's' : ''}`,
    inProgress: (n: number) => `${n} en cours`,
    blocked: (n: number) => `${n} bloquée${n > 1 ? 's' : ''}`,
    running: (n: number) => `${n} chaîne${n > 1 ? 's' : ''} en exécution`,
  },
  taskStatus: {
    pending: 'À faire',
    in_progress: 'En cours',
    blocked: 'Bloquée',
    completed: 'Terminée',
    failed: 'Échec',
  } as Record<string, string>,
  runLabel: {
    running: 'En exécution',
    completed: 'Terminée',
    failed: 'Échec',
    cancelled: 'Annulée',
    budget_exceeded: 'Budget dépassé',
  } as Record<string, string>,
}
