/** Visible wording of the work dashboard, in one place (DESIGN.md §0). */
export const WORK_TEXT = {
  title: 'Mes tâches',
  day: 'Ma journée',
  showAll: (n: number) => `Afficher les ${n}`,
  showLess: 'Réduire',
  dayEmpty: 'Rien de prévu pour aujourd’hui',
  dayEmptyHint: 'Ajoute des tâches depuis « À prendre » ou « En cours » : elles se rangent ici, dans l’ordre où tu veux les faire.',
  inProgress: 'En cours',
  inProgressEmpty: 'Aucune tâche en cours.',
  next: 'À prendre',
  nextEmpty: 'Aucun plan actif n’a de tâche prête.',
  chains: 'Plans à lancer',
  blocked: 'Bloquées',
  addToDay: 'Ajouter à ma journée',
  /** Short label of the visible button; its accessible name stays `addToDay`. */
  add: 'Ajouter',
  removeFromDay: 'Retirer de ma journée',
  moveUp: 'Monter',
  moveDown: 'Descendre',
  start: 'Démarrer',
  complete: 'Terminer',
  completeAria: (t: string) => `Marquer « ${t} » comme terminée`,
  launch: 'Lancer',
  relaunch: 'Relancer',
  launching: 'Lancement…',
  launched: 'Plan lancé',
  started: 'Tâche démarrée',
  completed: 'Tâche terminée',
  actionFailed: 'L’action n’a pas abouti.',
  neverRun: 'Jamais lancée',
  untitled: 'Tâche sans titre',
  loadError: 'Le tableau de bord n’a pas pu être chargé.',
  retry: 'Réessayer',
  stale: 'Actualisation impossible : les données affichées peuvent être périmées.',
  taskStatus: {
    pending: 'À faire',
    in_progress: 'En cours',
    blocked: 'Bloquée',
    completed: 'Terminée',
    failed: 'Échec',
  } as Record<string, string>,
  runLabel: {
    running: 'En exécution',
    completed: 'Terminée',
    failed: 'Échec',
    cancelled: 'Annulée',
    budget_exceeded: 'Budget dépassé',
  } as Record<string, string>,
}
