import { useMemo } from 'react'
import { useT } from '@/i18n'
import type { TimelineLabels } from '@/components/timeline'

/** The words of the timeline in the reader's language (the component itself only knows English defaults). */
export function useTimelineLabels(): TimelineLabels {
  const { t } = useT()
  return useMemo(
    () => ({
      status: {
        running: t('session.timeline.status.running'),
        done: t('session.timeline.status.done'),
        error: t('session.timeline.status.error'),
        blocked: t('session.timeline.status.blocked'),
        cancelled: t('session.timeline.status.cancelled'),
        pending: t('session.timeline.status.pending'),
        unknown: t('session.timeline.status.unknown'),
      },
      empty: t('session.timeline.empty'),
      emptyHint: t('session.timeline.emptyHint'),
      earlier: t('session.timeline.earlier', { n: '{n}' }),
      list: t('session.timeline.title'),
      calls: t('session.timeline.calls'),
      peak: t('session.timeline.peak'),
      parallel: t('session.timeline.parallel'),
      idle: t('session.timeline.idle'),
      trace: {
        label: t('session.timeline.trace.label'),
        spans: t('session.timeline.trace.spans', { n: '{n}' }),
        zoomIn: t('session.timeline.trace.zoomIn'),
        zoomOut: t('session.timeline.trace.zoomOut'),
        fit: t('session.timeline.trace.fit'),
        follow: t('session.timeline.trace.follow'),
        help: t('session.timeline.trace.help'),
        helpTouch: t('session.timeline.trace.helpTouch'),
        overview: t('session.timeline.trace.overview'),
        window: t('session.timeline.trace.window'),
        ruler: t('session.timeline.trace.ruler'),
        column: t('session.timeline.trace.column'),
        expand: t('session.timeline.trace.expand'),
        collapse: t('session.timeline.trace.collapse'),
        loading: t('session.timeline.trace.loading', { loaded: '{loaded}', total: '{total}' }),
        loadingStart: t('session.timeline.trace.loadingStart'),
        failed: t('session.timeline.trace.failed'),
        failedAll: t('session.timeline.trace.failedAll'),
        retry: t('session.timeline.trace.retry'),
        noDate: t('session.timeline.trace.noDate'),
        child: t('session.timeline.trace.child'),
        relay: t('session.timeline.trace.relay'),
        kind: {
          request: t('session.timeline.trace.kind.request'),
          tool: t('session.timeline.trace.kind.tool'),
          agent: t('session.timeline.trace.kind.agent'),
          permission: t('session.timeline.trace.kind.permission'),
          error: t('session.timeline.trace.kind.error'),
          marker: t('session.timeline.trace.kind.marker'),
          run: t('session.timeline.trace.kind.run'),
          routing: t('session.timeline.trace.kind.routing'),
          plan: t('session.timeline.trace.kind.plan'),
          task: t('session.timeline.trace.kind.task'),
          step: t('session.timeline.trace.kind.step'),
        },
        detail: {
          title: t('session.timeline.trace.detail.title'),
          close: t('session.timeline.trace.detail.close'),
          total: t('session.timeline.trace.detail.total'),
          self: t('session.timeline.trace.detail.self'),
          start: t('session.timeline.trace.detail.start'),
          end: t('session.timeline.trace.detail.end'),
          running: t('session.timeline.trace.detail.running'),
          status: t('session.timeline.trace.detail.status'),
          kind: t('session.timeline.trace.detail.kind'),
          model: t('session.timeline.trace.detail.model'),
          provider: t('session.timeline.trace.detail.provider'),
          input: t('session.timeline.trace.detail.input'),
          output: t('session.timeline.trace.detail.output'),
          showMore: t('session.timeline.trace.detail.showMore'),
          showLess: t('session.timeline.trace.detail.showLess'),
          goTo: t('session.timeline.trace.detail.goTo'),
          openSession: t('session.timeline.trace.detail.openSession'),
          zoom: t('session.timeline.trace.detail.zoom'),
          notRun: t('session.timeline.trace.detail.notRun'),
          runUnseen: t('session.timeline.trace.detail.runUnseen'),
          incomplete: t('session.timeline.trace.detail.incomplete'),
        },
      },
    }),
    [t],
  )
}
